### PR TITLE
Project can now use java17 and should be OK with 21 as well

### PR DESCRIPTION
**Pull request by SorenAndersenCrowdstrike**

### CODE REVIEW

**Review by srdo-cs — APPROVED** [review]
Looks good, will assume you've tried building/running this with these changes.

**Review by srdo-cs — COMMENTED** [review]
You need to update this path too https://github.com/humio/humio-ingest-load-test/blob/master/Makefile#L8 (it's scala-2.13 due to the Scala upgrade you did) 

Probably best to do a quick scan for other references to 2.12 in the code

**Comment by SorenAndersenCrowdstrike** [comment]
> You need to update this path too https://github.com/humio/humio-ingest-load-test/blob/master/Makefile#L8 (it's scala-2.13 due to the Scala upgrade you did)
> 
> Probably best to do a quick scan for other references to 2.12 in the code

Nice catch! Found a bunch of 2.12's in the code. Fixing it now.

**Comment by SorenAndersenCrowdstrike** [comment]
> Looks good, will assume you've tried building/running this with these changes.

Yes - I ran it w. Java17 and saw data being ingested on the target server. :)

**Comment by schofield** [comment]
Cherry picked from and merged with base image changes in #22

**Pull request closed without merging**
